### PR TITLE
Fix rails 4.2 failing specs

### PR DESCRIPTION
**Pull request by jlurena**

### CODE REVIEW

**Comment by mhgbrown** [comment]
I think what's causing the root of the [problem](https://github.com/mhgbrown/cached_resource/actions/runs/9842904452/job/27172904446) is that setting `concurrent_write` doesn't re-require `concurrent/promise` and that's necessary for certain Ruby/Rails/whatever combinations. After requiring `concurrent/promise` [explicitly in the spec helper](https://github.com/mhgbrown/cached_resource/blob/68-update-rspecs-and-ci/spec/spec_helper.rb#L6), [the build passes](https://github.com/mhgbrown/cached_resource/actions/runs/9843410324). 

Does that sound right? I can look into ensuring that changing `concurrent_write` will require `concurrent/promise`

**Comment by jlurena** [comment]
Ah nice. Thanks..it's hard for me to test as I can't install ruby < 2.7 in my machine

**Comment by mhgbrown** [comment]
Got it, I'll get something going.

**Comment by mhgbrown** [comment]
Should we close this in favor of https://github.com/mhgbrown/cached_resource/pull/70?

**Comment by jlurena** [comment]
Yeah

**Pull request closed without merging**
