### PR TITLE
Fix resource classes with descendants

### PR DESCRIPTION
**Pull request by turboladen**
After including cached_resource into my project, a bunch of tests
started failing. After some poking around, I found this Rails bug:
https://github.com/rails/rails/issues/3364#issuecomment-116636395

...then found that wasn't happening in cached_resource. Fixing this
fixed the tests for my Rails project.

### CODE REVIEW

**Comment by Daniel-ltw** [comment]
👍

**Comment by mhgbrown** [comment]
Nice one. Will get it out hopefully by EOD euro time.

**Comment by mhgbrown** [comment]
Or sooner 😉 https://rubygems.org/gems/cached_resource/versions/5.0.1

**Comment by turboladen** [comment]
Sweet! Thank you!

**Pull request merged**
