### PR TITLE
[ISSUE-26] Async writes using concurrent-ruby

### PR DESCRIPTION
**Pull request by jlurena**
## Summary
Resolves https://github.com/mhgbrown/cached_resource/issues/26 . Async writes with `concurrent-ruby`. 
Made it optional and configurable

### CODE REVIEW

**Comment by jlurena** [comment]
Need to write specs, writing specs for concurrent use cases is hard. Any tips would be appreciated

**Comment by jlurena** [comment]
@mhgbrown this is ready

**Comment by mhgbrown** [comment]
@jlurena thanks! I'll take a look soon

**Review by mhgbrown — APPROVED** [review]
Looks great, thank you. I'll merge it

**Pull request merged**
